name: hello-github-actions
run-name: ${{ github.actor }} is testing actions
on:
  schedule:
    - cron: '0/45 * * * *'
env:
  GIT_AUTHOR_NAME: ${{ github.actor }}
  GIT_AUTHOR_EMAIL: noemail@example.com
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python sample_script.py > out/`date +"%Y-%m-%d.%H-%M.json"`
      - run: |
          git config user.email $GIT_AUTHOR_NAME
          git config user.name $GIT_AUTHOR_EMAIL
          git add out
          git commit -m 'Actions output'
