name: hello-github-actions
run-name: ${{ github.actor }} is testing actions
on:
  schedule:
    - cron: '0/20 * * * *'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
      - run: python sample_script.py > out/`date +"%Y-%m-%d.%H-%M.json"`
      - run: git add out
      - run: git commit -m 'Actions output'
